apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agriya-backend
  namespace: agriya
spec:
  rules:
    - host: api.agriya.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: agriya-backend
                port:
                  number: 80
